# Generated by Django 5.2.8 on 2025-11-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('rank', models.CharField(max_length=100, verbose_name='Ранг')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Бонусные баллы')),
                ('total_hours_played', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего часов игры')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
