# Generated by Django 5.2.8 on 2025-11-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0001_initial'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час (₽)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['hourly_rate'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя гостя'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='Гостевая сессия'),
        ),
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='loyalty.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='place',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='crm_core.tariff', verbose_name='Тариф'),
        ),
    ]
