# Generated by Django 5.2.8 on 2025-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0002_tariff_session_guest_name_session_is_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Basic', 'Basic'), ('Bootcamp', 'Bootcamp')], default='Basic', max_length=20, verbose_name='Тип места'),
        ),
    ]
