# Generated by Django 5.2.8 on 2025-11-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0003_place_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='scheduled_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемое время окончания'),
        ),
    ]
