# Generated by Django 5.2.8 on 2025-11-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0004_session_scheduled_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
            },
        ),
    ]
