# Generated by Django 5.2.8 on 2025-11-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0005_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_time'], 'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AddField(
            model_name='session',
            name='discount_applied',
            field=models.PositiveIntegerField(default=0, verbose_name='Примененная скидка (%)'),
        ),
        migrations.AddField(
            model_name='session',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_core.promotion', verbose_name='Примененная акция'),
        ),
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость (₽)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец сессии'),
        ),
        migrations.AlterField(
            model_name='session',
            name='scheduled_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированное окончание'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(verbose_name='Начало сессии'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
